name: SimpleHungerGames
main: tk.shanebee.hg.HG
authors: [bob7l, Spoopy, ShaneBee, paralin]
description: Simplified version of the HG plugin
version: '${project.version}'
website: https://bitbucket.org/ShaneBeeStudios/hungergames
api-version: '1.13'
softdepend: [Multiverse-Core, MultiWorld, My_Worlds, GoldenEnchants, PlaceholderAPI]

commands:
  hg:
    description: HungerGames Base command
